[build]
command = 'hugo'
publish = 'public'

[build.environment]
HUGO_VERSION = '0.101.0'
NETLIFY_BUILD_IMAGE = "ubuntu-noble-24.04"

[context]
[context.branch-deploy]
command = 'hugo -F -b $DEPLOY_PRIME_URL'

[context.deploy-preview]
command = 'hugo -F -b $DEPLOY_PRIME_URL'

[context.production]
[context.production.environment]
HUGO_ENV = 'production'
